[WEB3-2] implement agenda to schedule jobs
runtimerevolution/web3-roulette pull request #53
Opened 2023-07-17 16:35 UTC by ti-martins

---
name: "Pull Request"
about: "implement agenda to schedule jobs, implement generate winners job"
title: "[WEB3-2] Schedule winners generation"
---

# Description

implement agenda to schedule jobs
implement generateWinners job

Ticket: https://runtime-revolution.atlassian.net/browse/WEB3-XX

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

job creation should be automatic on respective actions

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-07-17 16:56 UTC, marciammart requested changes

2023-07-17 16:56 UTC, marciammart commented on packages/node-app/src/controllers/giveaway.controller.ts
> +    await scheduleWinnerGeneration(giveaway);
Can we move the schedule to after we call the contract, just in case the contract fails and the giveaway is not created successfully?

2023-07-17 16:56 UTC, marciammart commented on packages/node-app/src/utils/agenda.utils.ts
> +agenda.define('createGiveaway', async (job) => {
```suggestion
agenda.define('generateGiveawayWinners', async (job) => {
```

2023-07-17 17:17 UTC, marciammart approved these changes

2023-07-18 08:05 UTC, goncaloadolfo approved these changes

2023-07-19 09:44 UTC, merged